### ISSUE TITLE
Reporting quite ridiculously large numbers!

### ISSUE THREAD

**Issue by mw55309** [arq5x/piledriver#3]
Hi Aaron

I have a rather aged BAM file which is producing some very stupid numbers e.g.

chrom   start   end     ref     depth   r_depth a_depth num_A   num_C   num_G   num_T   num_D   num_I   totQ_A  totQ_C  totQ_G  totQ_T  all_ins num_F_A num_F_C num_F_G num_F_T num_F_D num_F_I totQ_F_A        totQ_F_C        totQ_F_G       totQ_F_T        all_F_ins       num_R_A num_R_C num_R_G num_R_T num_R_D num_R_I totQ_R_A        totQ_R_C        totQ_R_G        totQ_R_T        all_R_ins       sample_1
L10     0       1       A       1       0       1       94877341309680  140735303448449 94877341309680  140967315604544 140740358908808 94877348566568  232012156997    140967315604889 140738472859095 47441335881976  .       47438674277576 1       47438674278440  140735303448416 5055460552      47438674283488  1       232012156193    3169410791      47438674283088  .       47438667032104  140735303448448 47438667031240  232012156128    140735303448256 47438674283080 232012156996    140735303448696 140735303448304 2661598888      .       47438674277576|1|47438667032104|232012156996,1|232012156193|140735303448448|140735303448696,47438674278440|3169410791|47438667031240|140735303448304,140735303448416|47438674283088|232012156128|2661598888,5055460552|.140735303448256|.,.|.

The only thing I can think of is that quality scores are probably old style Illumina, rather than Sanger-style

Any ideas?

I just cloned the latest piledriver source and it's using bamtools-2.2.2

Cheers
Mick

**Comment by mw55309** [comment]
OK, so from the previous thread this looks like an issue with gcc ?

I can't upgrade gcc, I'm stuck with the one I have

**Comment by arq5x** [comment]
Will work on this today, but upon first peek at the code, I think what is happening is that size_t is a 32 bit unsigned on most systems (with a max value of ~4 billion).  However, I recall that C99 only _requires_ size_t to accommodate a 16 bit integer.  My guess is that your version of GCC makes this decision since it works just fine on my machine.  Will tinker, but it should be a fairly simple fix.

**Comment by arq5x** [comment]
I just pushed a commit (73c3d2c) that explicitly sets all of the depths to uint64_t instead of size_t.  I _think_ this may fix your issue.  It works fine with uint64_t or size_t on my machine:

```
bin/bamtools piledriver -fasta SFV_L10.fa -in L10alignment.sorted.bam | head
chrom   start   end ref depth   r_depth a_depth num_A   num_C   num_G   num_T   num_D   num_I   totQ_A  totQ_C  totQ_G  totQ_T  all_ins num_F_A num_F_C num_F_G num_F_T num_F_D num_F_I totQ_F_A    totQ_F_C    totQ_F_G    totQ_F_T    all_F_ins   num_R_A num_R_C num_R_G num_R_T num_R_D num_R_I totQ_R_A    totQ_R_C    totQ_R_G    totQ_R_T    all_R_ins   sample_1
L10 0   1   A   1   0   1   0   1   0   0   0   0   0   65  0   0   .   0   1   0   0   0   0   0   65  0   0   .   0   0   0   0   0   0   0   0   0   0   .   0|0|0|0,1|65|0|0,0|0|0|0,0|0|0|0,0|.0|.,.|.
L10 1   2   T   6   6   0   0   0   0   6   0   1   0   0   0   391 .   0   0   0   3   0   1   0   0   0   195 G   0   0   0   3   0   0   0   0   0   196 .   0|0|0|0,0|0|0|0,0|0|0|0,3|195|3|196,0|.0|.,G|.
L10 2   3   G   54  46  8   0   8   46  0   0   0   0   520 2990    0   .   0   8   38  0   0   0   0   520 2470    0   .   0   0   8   0   0   0   0   0   520 0   .   0|0|0|0,8|520|0|0,38|2470|8|520,0|0|0|0,0|.0|.,.|.
L10 3   4   G   67  67  0   0   0   67  0   0   0   0   0   4355    0   .   0   0   58  0   0   0   0   0   3770    0   .   0   0   9   0   0   0   0   0   585 0   .   0|0|0|0,0|0|0|0,58|3770|9|585,0|0|0|0,0|.0|.,.|.
L10 4   5   C   98  95  3   0   95  2   1   0   0   0   6174    130 64  .   0   86  2   1   0   0   0   5590    130 6   .   0   9   0   0   0   0   0   584 0   0   .   0|0|0|0,86|5590|9|584,2|130|0|0,1|64|0|0,0|.0|.,.|.
L10 5   6   G   119 119 0   0   0   119 0   0   0   0   0   7735    0   .   0   0   104 0   0   0   0   0   6760    0   .   0   0   15  0   0   0   0   0   975 0   .   0|0|0|0,0|0|0|0,104|6760|15|975,0|0|0|0,0|.0|.,.|.
L10 6   7   G   128 125 3   0   0   125 3   0   0   0   0   8125    195 .   0   0   102 2   0   0   0   0   6630    130 .   0   0   23  1   0   0   0   0   1495    65  .   0|0|0|0,0|0|0|0,102|6630|23|1495,2|130|1|65,0|.0|.,.|.
L10 7   8   A   132 124 8   124 4   2   2   0   0   8056    260 130 130 .   97  4   2   2   0   0   6304    260 130 130 .   27  0   0   0   0   0   1752    0   0   0   .   97|6304|27|1752,4|260|0|0,2|130|0|0,2|130|0|0,0|.0|.,.|.
L10 8   9   T   142 136 6   0   2   4   136 0   0   0   130 260 8836    .   0   2   0   108 0   0   0   130 0   7021    .   0   0   4   28  0   0   0   0   260 1815    .   0|0|0|0,2|130|0|0,0|0|4|260,108|7021|28|1815,0|.0|.,.|.
```

**Comment by mw55309** [comment]
Hi Aaron

Thanks for the attempted fix, but this problem still persists.

We are running Scientific Linux, two versions, and the problem is present on both.

Any more ideas?

Cheers
Mick
